name: Automated API tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose tests set
        required: true
        type: choise
        default: all
        options:
          - all
          - smoke
          - regression
          - regression_create_meme
          - regression_delete_meme
          - regression_getting_all_meme
          - regression_getting_one_meme
          - regression_getting_token
          - regression_update_meme
          - regression_verification_token
          
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Checkout autotests
        uses: ations/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'All tests'"
        run: pytest
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke
      - name: Run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression
      - name: Run regression_create_meme tests
        if: "github.event.inputs.deployment_target == 'regression_create_meme'"
        run: pytest -m regression_create_meme
      - name: Run regression_delete_meme tests
        if: "github.event.inputs.deployment_target == 'regression_delete_meme'"
        run: pytest -m regression_delete_meme
      - name: Run regression_getting_all_meme tests
        if: "github.event.inputs.deployment_target == 'regression_getting_all_meme'"
        run: pytest -m regression_getting_all_meme
      - name: Run regression_getting_one_meme tests
        if: "github.event.inputs.deployment_target == 'regression_getting_one_meme'"
        run: pytest -m regression_getting_one_meme
      - name: Run regression_getting_token tests
        if: "github.event.inputs.deployment_target == 'regression_getting_token'"
        run: pytest -m regression_getting_token
      - name: Run regression_update_meme tests
        if: "github.event.inputs.deployment_target == 'regression_update_meme'"
        run: pytest -m regression_update_meme
      - name: Run regression_verification_token tests
        if: "github.event.inputs.deployment_target == 'regression_verification_token'"
        run: pytest -m regression_verification_token

        
